### Test GET
GET http://localhost:8000/helper/health
Content-Type: application/json

###

### Test POST
POST http://localhost:8000/helper/health/
Content-Type: application/json

{
    "health": true
}

###

### Test PATCH
PATCH http://localhost:8000/helper/health/
Content-Type: application/json

{
    "id": 3,
    "health": false
}

###

### Test DELETE
DELETE http://localhost:8000/helper/health/
Content-Type: application/json





